### ISSUE TITLE
Add more methods to TimeSeries

### ISSUE THREAD

**Issue by brennan-ae** [slac207/cs207project#13]
... and confirm the old ones are implemented as described:

Part 1: Add some more methods

Your TimeSeries class should be, by now, a well documented, well tested, mutable, class which implements:

**getitem**: to get a value for a given index (should have done this)
**setitem**: set the value for the given index (should have done this)
**contains**: is a value in the values (NEW)
**iter**: iterates over values. (This might have iterated over tuples of (time, value) pairs earlier (should have done this)
values: returns a numpy array of values (should have done this)
itervalues: returns an iterator over them (NEW)
times: returns a numpy array of times (NEW)
itertimes: returns an iterator over them (should have done this)
items: returns a list of time-value tuple pairs (NEW)
iteritems: returns an iterator over these (should have done this)
**len**: returns a length. (should have done this)
**repr**: abbreviating string representation (should have done this)

**Comment by brennan-ae** [comment]
Also, bug #6 can probably be bundled with this.

**Comment by jsm09** [comment]
Isn't this one the same as #22

**Comment by sanoke** [comment]
You're exactly right @jsm09. During our group meeting, we assigned this task to you... do you want to close this issue out?

**Comment by jsm09** [comment]
Sure, I'll leave the other one open. Thanks
