### ISSUE TITLE
Write tests for TimeSeries.py

### ISSUE THREAD

**Issue by sanoke** [slac207/cs207project#18]
From [Project Spec 1](https://github.com/slac207/cs207project/blob/master/projectReq/project1.pdf),

> Test your constructor and the other methods you have defined. (See the requirements for the constructor above: you dont need to formally test against the sequence protocol, but testing common sequences is key. Also test against things like ranges, which are "unrealized" sequences.)

In these tests, include _smoke tests_.

**Comment by sanoke** [comment]
I think @cocochrane has already written a lot of the tests (including smoke tests). But @jsm09 I'm going to leave this issue open so you can update us on how things are going + let us know if you need any help. Feel free to close the issue when you're done testing.

**Comment by jsm09** [comment]
Since it looks like she wrote the tests, what should I be doing on this issue?

**Comment by jsm09** [comment]
@cocochrane Courtney, where did you leave off? Did you write the TimeSeries tests for weeks 1 through 4?

**Comment by cocochrane** [comment]
I should have almost all the necessary tests for week 1-2 (excluding the smoke test because I thought that was just something to try, not something to add as a unit test). It would be awesome if you wanted to check and make sure I didn't leave anything out? I think I saw that Laura wrote a str/repr check which is great because I forgot to do those

**Comment by cocochrane** [comment]
@jsm09 Do we think we can close this at this point?

**Comment by jsm09** [comment]
@cocochrane 
Hmm, there are some additional tests needed for weeks 3 and 4 I think? At least, the linear interpolation method will need tests. Should we make that a different issue and close this one?

**Comment by sanoke** [comment]
@jsm09 @cocochrane I still need to write the linear interpolation stuff, which I will work on tomorrow. We can leave this open and I'll update with info about the tests I write for that part.

**Comment by jsm09** [comment]
Closing this issue @cocochrane @sanoke
