### ISSUE TITLE
Write tests for ArrayTimeSeries.py

### ISSUE THREAD

**Issue by sanoke** [slac207/cs207project#21]
From [Project Spec 2](https://github.com/slac207/cs207project/blob/master/projectReq/project2.pdf),

> Make sure that any doctests and tests you wrote before to test all kinds of sequences as input still pass. (If you didn't write any, how do you know your `timeseries` class from last time is any good? We'll be testing your code by running our own tests as well!)

@jsm09 How is this going? Do you need any of us to help?

**Comment by jsm09** [comment]
Sure if you have time feel free to help out with this. Then I can get started on the re-parenting part sooner.

**Comment by jsm09** [comment]
@sanoke I pushed some first pass tests (with comments). Please take a look and add to them (or get someone else to if you like)! I'd appreciate the help.

**Comment by jsm09** [comment]
@sanoke Done with this item. Please go ahead and check them over, or add any that I may have missed. Thanks!

**Comment by sanoke** [comment]
I'll have a look tomorrow evening @jsm09, if that's not too late.

**Comment by jsm09** [comment]
Closing this issue @sanoke
