### ISSUE TITLE
Implement a Mean and Standard Deviation (EC)

### ISSUE THREAD

**Issue by sanoke** [slac207/cs207project#27]
## From the [Project Spec 5](https://github.com/slac207/cs207project/blob/master/projectReq/project5.pdf)

Add `mean` and `std` method interfaces at the appropriate places in the hierarchy. These methods should return floating point numbers (an optional `chunk` argument is needed in some cases). Also add an `online_mean` and `online_std` for `StreamTimeSeriesInterface` time-series, which themselves return the appropriate time-series. These "online" methods should return new `SimulatedTimeSeries` of the appropriate type, and when `produce` is called on them, should produce `chunk` means and standard deviations, starting from the current state of the time series. (Notice that this will be the meaning of `mean` and `std` with non default `chunk` as well: i.e., the last chunk observations' statistic.)

Put this code into your project repo.

**Comment by brennan-ae** [comment]
In pull-requests #53, #54, #55
