### ISSUE TITLE
Test dunders `iter` and `itertimes` and `iteritems`.

### ISSUE THREAD

**Issue by sanoke** [slac207/cs207project#4]
Was reviewing the Project Spec 2 (see [projectReq/project2.pdf](https://github.com/slac207/cs207project/blob/master/projectReq/project2.pdf)) and it mentioned that the `__iter__()` methods should have some _basic_ testing:

> To test these [`iter` methods], check both the types of the results and the answers you expect.

Just checking to see if you did this, and if you could update the issue to let us know! Thanks!

**Comment by cocochrane** [comment]
I did this!
