### ISSUE TITLE
Generalize the ArrayTimeSeries class to take sequences instead of numpy.array

### ISSUE THREAD

**Issue by sanoke** [slac207/cs207project#5]
**Task (from [Project Spec 3](https://github.com/slac207/cs207project/blob/master/projectReq/project3.pdf))** Please change the class constructor to take two sequences as input. The call signature should look something like this now:

``` python
# order of arguments has changed because no default
def __init__(self, times, values): # notice no default for times now
  ...
```

Make sure you implement the `__iter__`, `itertimes`, `iteritems`, `__len__`, `__getitem__` and `__setitem__` (the latter two take an index and get a value and set a value correspoinding to that index respectively..note I say index, not time).

---

**Details** Rewrite your `ArrayTimeSeries` class, with two goals:
- We want you to store two arrays internally, even if you only have a single vector of values. The first should represent a list of time points, and the other should be a set of values.
- Go ahead and use `numpy` arrays for the internal storage.

The goal of your new arrays is to work something like a cross between an array and a dictionary. Your class is an ordered container, where each time point should be monotonically increasing (you don't need to enforce this right now, but you're welcome to if you want). It's like a sequence or array in this way.

**Comment by brennan-ae** [comment]
@cocochrane @lshen2009 
Is this closed now?
