### ISSUE TITLE
P8- Create StorageManagerInterface

### ISSUE THREAD

**Issue by cocochrane** [slac207/cs207project#59]
Create a new StorageManagerInterface which has abstract methods:

1. store(id:int/string, t:SizedContainerTimeSeriesInterface)->SizedContainerTimeSeriesInterface
2. size(id:int/string)->int
3. get(id:int/string)->SizedContainerTimeSeriesInterface

Notice that one implication of this interface is that we are also letting the storage manager handle the in-memory needs of our time series.

**Comment by brennan-ae** [comment]
Addressed in Pull Request #68
