### ISSUE TITLE
`itertimes` and `iteritems` aren't supposed to be dunders?

### ISSUE THREAD

**Issue by sanoke** [slac207/cs207project#6]
@cocochrane I don't think that `itertimes` and `iteritems` are supposed to be dunders...? I'm guessing by the way they were referred to in the [third project specification](https://iacs-cs207.github.io/cs207-2016/projects/project3.html). Change them to regular functions (without the underscores)? What do other people think?

**Comment by cocochrane** [comment]
Fixed
