### ISSUE TITLE
P6- Write Tests for BinarySearchTree

### ISSUE THREAD

**Issue by cocochrane** [slac207/cs207project#63]
My suggestion is to first implement the database as an unbalanced binary search tree: basically you need to cross the t's and dot the i's on the lab. The code can be more elegant, and you must document it better, and test it extensively.

**Comment by jsm09** [comment]
Smoke tests has been written

**Comment by jsm09** [comment]
Okay - just added a bunch of tests. Currently we're at 99% coverage for RedBlackTree.py

**Comment by jsm09** [comment]
Closing this issue
