### ISSUE TITLE
P6- Make new module cs207rbtree, make pip installable, and integrate coveralls and travis-ci

### ISSUE THREAD

**Issue by cocochrane** [slac207/cs207project#64]
Construct a functional red-black tree database, in a new python module, cs207rbtree. Develop this in the cs207project repo, or optionally another repo of your choice, whose name is linked from the cs207project README.md. This module should be pip installable, and properly travis-ci'ed and coveralled.

**Comment by jsm09** [comment]
I've created a new branch rbtree and added in a new directory, cs207rbtree. Right now it just has the code from lab10. I added all classes to the same file, but I can split these into more files later if we want.

**Comment by jsm09** [comment]
Update: I have confirmed that Travis and Coveralls are working properly with the new module.

**Comment by jsm09** [comment]
Update: docstrings have been completed for all methods, as well as smoke tests for the unbalanced tree implementation

**Comment by cocochrane** [comment]
@sanoke @jsm09 I wrote 3 functions (a tree traversal, a "find nodes with key less than", and a "find nodes with key greater than") for the similarity part with the unbalanced tree. But, really we only need the "find nodes with key less than" to also be implemented in the RedBlack Tree. Just a heads up
