### ISSUE TITLE
P9 Vantage Point calculations - replace binary tree with our red-black tree implementation

### ISSUE THREAD

**Issue by jsm09** [slac207/cs207project#72]
(1). If you have completed it, replace the unbalanced binary tree database by a red black one. The subsequent steps should not care if the underlying database is unbalanced binary-tree or red-black tree, so that provides you a path to move forward in-case you are having issues with the red-black-tree database (which is hard!)

**Comment by brennan-ae** [comment]
Completed in pull request #94
